config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :events
  resources :users do
    resources :avatars, only: [:create]
  end
  resources :attendances

  #define the Admin path
  resources :admins
  namespace :admin do
    resources :users
    resources :events
  end
    # Defines the root path route ("/")
  root to: "events#index"
  #Stripe Path
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    #after_create :welcome_send

    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validate do
    errors.add(:start_date, "ne peut pas être dans le passé") if start_date && start_date < Time.now
  end
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0}
  validate do
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "doit être un multiple de 5")
    end
  end
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User', foreign_key: 'admin_id', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
    
    validates :email, presence: true
    has_many :attendances
    has_many :events, through: :attendances
    has_one_attached :avatar
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
      end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
    def index
      @users = User.all
    end
    def create

    end
    def edit
      @user = User.find(params[:id])
    end
    def update
      @user = User.find(params[:id])
      if @user.update(first_name: params[:user][:first_name],
        last_name: params[:user][:last_name],
        description: params[:user][:description])
        flash[:notice] = "Gossip créé avec succès!"
        redirect_to admin_users_path, notice: "Utilisateur Mis a jour !"
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path, notice: "Utilisateur supprimé avec succès!"
    end
    private
    def require_admin
      unless current_user.is_admin?
        flash[:alert] = "Vous n'avez pas l'autorisation d'accéder à cette page."
        redirect_to root_path
      end
    end
  end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :require_admin
    def index
        @user = current_user
    end

    private

    def require_admin
      unless current_user.is_admin
        flash[:alert] = "Vous n'avez pas l'autorisation d'accéder à cette page."
        redirect_to root_path
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    before_action :authenticate_user!
    def index
        @user = current_user
    end
    def new
        @user = current_user
        #@event = Event.find(params[:id])
    end
    def create

    end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def create
      @user = User.find(params[:user_id])
      @user.avatar.attach(params[:avatar])
      redirect_to user_path(@user)
    end
  end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    @event_id = params[:event_id]
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      metadata: {
        event_id: @event_id
      },
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end
    
      def success
        @session = Stripe::Checkout::Session.retrieve(params[:session_id])
        @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
        @event_id = @session.metadata.event_id
      end
    
      def cancel
      end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, exept: [:index]
    def index
        @events = Event.all
    end
    def show
        @event = Event.includes(:admin).find(params[:id])
    end
    def new
        #besoin de rien mon new est un form qui fait un post create
        @user = current_user
    end
    def create
        @user = current_user
        @event = Event.new(event_params.merge(admin: current_user))
      
          if @event.save # essaie de sauvegarder en base
            # si ça marche, il redirige vers la page d'index du site
            flash[:notice] = "évènement créé avec succès!"
            redirect_to events_path
          else
            # sinon, il render la view new (qui est celle sur laquelle on est déjà)
            flash[:notice] = "évènement pas crée CHEH!"
            render :new
          end
    end

    private

    def event_params
        params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]
    before_action :good_user, only: [:show]
    
    def show
        @user = User.find(params[:id])
        @admins = Event.all.where(admin_id: params[:id])
    end

    private

    def good_user
      unless current_user == User.find(params[:id])
        flash[:danger] = "Please log in."
        redirect_to events_path
      end
    end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
<%= form_for(@user, url: admin_user_path(@user), method: :patch, html: { class: "form-signin mt-3" }) do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Updater le profil de <%=@user.email%></h1>
        <div class="form-group">
          <%= f.label  :first_name, "Prénom" %><br />
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label  :last_name, "Nom" %><br />
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label  :description, "Description" %><br />
          <%= f.text_field :description, autofocus: true, class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "éditer", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h2>Liste des users</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                  <th>nom</th>
                  <th>prénom</th>
                  <th>mail</th>
                  <th>description</th>
                  <th>id</th>
                  <th>éditer</th>
                  <th>supprimer</th>
                  <th></th>
                </tr>
              </thead>
              <%@users.each do |user|%>
              <tbody>
                <tr>
                  <td><%=user.last_name%></td>
                  <td><%=user.first_name%></td>
                  <td><%=user.email%></td>
                  <td><%=user.description%></td>
                  <td><%=user.id%></td>
                  <td><%= link_to "éditer l'utilisateur", edit_admin_user_path(user), data: { turbo_method: :delete }, class: "btn btn-warning btn-lg small" %></td>
                  <td><%= button_to "Supprimer l'utilisateur", admin_user_path(user), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?" }, class: "btn btn-danger btn-lg small" %></td>
                </tr>
                <tr>
            <%end%>
        </table>
    </div>

app/views/admins/index.html.erb
<h1>index admin</h1>
        <%= link_to "gerer les users", admin_users_path, class:'btn btn-primary btn-lg' %>
        <%= link_to "gerer les events", admin_users_path, class:'btn btn-primary btn-lg' %>

app/views/attendances/index.html.erb
<p><%= @user.first_name%>
<%= @event_id%></p>
<p>index</p>

app/views/attendances/new.html.erb
<p><%= @user.first_name%>
<%= @event_id%></p>
<p>new</p>

app/views/checkout/cancel.html.erb
<div class="container text-center my-5"> 
    <h1>Echec</h1> 
    <p>Le paiement n'a pas abouti.</p> 
</div>

app/views/checkout/create.js.erb
var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
stripe.redirectToCheckout({
    sessionId: <%= @session.id %>
}).then(function (result) {
    console.log(result.error.message);
});

app/views/checkout/success.html.erb
<div class="container text-center my-5"> 
    <h1>Succès</h1> 
    <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p>
    <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p>
</div>

app/views/events/index.html.erb
<% if flash[:notice].present? %>
    <div class="alert alert-success text-center">
        <%= flash[:notice] %>
    </div>
<% end %>
<main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Chineur De moment</h1>
          <p>Bienvenue sur chineur de moment, la nouvelle application pour découvrir les derniers évènement branchés du moment</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Crée un évènement &raquo;</a></p>
        </div>
    </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
        <% @events.each do |event| %>

          <div class="col-md-4">
            <h2><%= event.title %></h2>
            <p><%= event.description %></p>
            <p>Location : <%= event.location %></p>
            <p class="small">Prix : <%= event.price %> €</p>
            <p><a class="btn btn-secondary" href="<%= event_path(event) %>" role="button">En Savoir + &raquo;</a></p>
                                 

        </div>
    <% end %>
    <hr>

    </div> <!-- /container -->

</main>

app/views/events/new.html.erb
<% if defined?(@event) && @event.errors.any? %>
  <div class="alert alert-danger text-center">
    <p>Erreur lors de la création du gossip : </p>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <p>Blablabla <%=current_user.first_name%></p>
            <%= form_tag(events_path, method: "post") do %>
            <div class="form-group">
                <%= label_tag :start_date, "Date de début" %>
                <%= datetime_local_field_tag 'event[start_date]', nil, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= label_tag :duration, "Durée" %>
                <%= number_field_tag 'event[duration]', nil, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= label_tag :title, "Titre" %>
                <%= text_field_tag 'event[title]', nil, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= label_tag :description, "Description" %>
                <%= text_area_tag 'event[description]', nil, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= label_tag :price, "Prix" %>
                <%= number_field_tag 'event[price]', nil, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= label_tag :location, "Lieu" %>
                <%= text_field_tag 'event[location]', nil, class: "form-control" %>
            </div>
            <br>
            <div class="form-group">
                <%= submit_tag "Créer l'événement", class: "btn btn-primary" %>
            </div>
            <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="d-flex h-100 text-center ">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <h1><%= @event.title %></h1>
        <p>
            Description : <%= @event.description %><br/>
            Nombre de Participant : jsp <br/>
            Créateur : <%=@event.admin.email%> <br/>
            date de début : <%= @event.start_date %><br/>
            date de fin : <%= @event.start_date + @event.duration.minute %><br/>
            lieu : <%= @event.location %><br/>
            prix : <%= @event.price %> €
        </p>
        <% if current_user != @event.admin %>
            <div class="col">
            <%= link_to "S'inscrire", new_attendance_path(@event.id), class: "btn btn-primary" %>
            <br>
            <%= button_to "Passer commande (NEXT GEN)", checkout_create_path(total: @event.price,event_id: @event_id), class: "btn btn-primary", remote: true %>
            </div>
        <%end%>
    </div>

<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChineurDeMoment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body data-turbo="false">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>



    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path  %>">Chineur De moment</a>      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Créer un event", new_event_path, class: "nav-link" %>            
          </li>                 
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
          <li class="nav-item mr-3 text-light">Je suis <%= current_user.first_name %></li>
          <% end %>
          <li class="nav-item dropdown mr-3">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profil</a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown03"> 
                <% if user_signed_in? %> 
                  <%= link_to "Mon profil", user_path(current_user.id), class: "dropdown-item" %>
                  <%= link_to "se deconnecter", destroy_user_session_path, method: :delete,data: {turbo: true,turbo_method: :delete,turbo_confirm: "Vous etes sure de vouloir vous déconnecter ?"}, class: "dropdown-item" %>
                <% else %>
                  <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>                  
                <% end %>
              </div>
          </li>       
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="d-flex h-100 text-center ">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <h1>Profil de <%= @user.first_name %>  <%= @user.last_name %></h1>
        <h3>Avatar actuel</h3>
        <%if @user.avatar.attached?%>
          <%= image_tag @user.avatar, alt: 'avatar', class:'img-thumbnail height:150px' %>
        <%else%>
          <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
        <%end%>
        <br><br>
          <h3>Changer d'avatar ?</h3>
          <%= form_tag user_avatars_path(@user), multipart: true do %>
            <%= file_field_tag :avatar %>
            <%= submit_tag "mettre à jour" %>
          <% end %>
        <br><br>
        <p>
            prénom : <%= @user.first_name %><br/>
            nom : <%= @user.last_name %><br/>
            description : <%= @user.description %><br/>
            e-mail : <%= @user.email %><br/>
        </p>
        <p>Vous souhaitez modifier votre Mail/Mot de passe ? </p>
        <div class="col">
        <%= link_to "Edit email / password", edit_user_registration_path, class:'btn btn-primary btn-lg' %>
        </div>
      <div class="container">
        <!-- Example row of columns -->
        <% @admins.each do |event| %>
        <div class="row">
          <div class="col-md-4">
            <h2><%= event.title %></h2>
            <p><%= event.description %></p>
            <a class="btn btn-secondary" href="<%= event_path(event) %>" role="button">Voir l'évènement &raquo;</a>
        </div>
        <% end %>
    </div>
<div>